function createfigure1(X1, YMatrix1)
%CREATEFIGURE1(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 29-Nov-2020 13:22:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Heading','Color',[0.4667 0.6745 0.1882]);
set(plot1(2),'DisplayName','Roll','Color',[0.7176 0.2745 1]);
set(plot1(3),'DisplayName','Pitch','Color',[0.9294 0.6941 0.1255]);

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');

